//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignerTool.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtorContact
    {
        public long DebtorContactID { get; set; }
        public long DebtorID { get; set; }
        public long ContactID { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Debtor Debtor { get; set; }
    }
}
