//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignerTool.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debtor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Debtor()
        {
            this.DebtorContacts = new HashSet<DebtorContact>();
        }
    
        public long DebtorID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebtorContact> DebtorContacts { get; set; }
    }
}
