//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignerTool.AppLogic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetting
    {
        public long SystemSettingID { get; set; }
        public string Setting { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public bool IsActive { get; set; }
    }
}
